version: "3.8"
services:
  database:
    container_name: mysql
    build: ./db
    volumes:
    - type: volume
      source: db
      target: /var/libs/mysql
  flask-app:
    container_name: flask-app
    build: ./flask-app
    depends_on:
    - "database"
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
volumes:
  db: